index:
    path: /
    controller: App\Infrastructure\Controller\HomeController::index

user_register:
    path: /user_register
    controller: App\Infrastructure\Controller\User\UserRegisterController::userRegister

user_login:
    path: /user_login
    controller: App\Infrastructure\Controller\User\UserLoginController::userLogin