home:
    path: /
    controller: App\Infrastructure\Controller\HomeController::home

user_register_page:
    path: /user_register_page
    controller: App\Infrastructure\Controller\RegisterPageRendererController::renderPage

user_register:
    methods: POST
    path: /user_register
    controller: App\Infrastructure\Controller\User\UserRegisterController::userRegister

user_login:
    methods: POST
    path: /user_login
    controller: App\Infrastructure\Controller\User\UserLoginController::userLogin

user_logout:
    methods: GET
    path: /user_logout
    controller: App\Infrastructure\Controller\User\UserLogoutController::userLogout

create_category:
    methods: POST
    path: /create_category
    controller: App\Infrastructure\Controller\Category\CreateCategoryController::createCategory

create_word:
    methods: POST
    path: /create_word
    controller: App\Infrastructure\Controller\Word\CreateWordController::createWord

check_answer:
    methods: POST
    path: /check_answer
    controller: App\Infrastructure\Controller\Word\CheckAnswerController::checkAnswer

practice:
    methods: POST
    path: /practice
    controller: App\Infrastructure\Controller\Category\PracticeController::practice

remove_category:
    methods: POST
    path: /remove_category
    controller: App\Infrastructure\Controller\Category\RemoveCategoryController::removeCategory

remove_word:
    methods: POST
    path: /remove_word
    controller: App\Infrastructure\Controller\Word\RemoveWordController::removeWord

start_demo:
    methods: GET
    path: /start_demo
    controller: App\Infrastructure\Controller\Demo\DemoController::startDemo
